### ISSUE TITLE
Build and run problems with JDK 21 and IntelliJ

### ISSUE THREAD

**Issue by bojanantonovic** [tomerr90/JavaVectorAPI-1#1]
Your code requires **huge** amount of work to partially compile. Working doesn't run. And it wasn't the usual issue with jdk.incubator.vector.

1) First was a problem with Java 21.

2) Then I was forced to introduce module-info.java:

```
module Vectors {
	requires jmh.core;
	requires jdk.incubator.vector;
	requires jdk.unsupported;
}
```

3) Adaptations to pom.xml, especially adding annotationProcessorPaths.

```
<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.12.1</version>
                <configuration>
                    <release>21</release>
                    <enablePreview>true</enablePreview>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.openjdk.jmh</groupId>
                            <artifactId>jmh-generator-annprocess</artifactId>
                            <version>1.35</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.2.5</version>
                <configuration>
                    <forkCount>1</forkCount>
                    <argLine>
                        --enable-preview
                    </argLine>
                </configuration>
            </plugin>
```

This was sufficient for a Maven clean install.

4) Running gave  java.lang.ClassNotFoundException: org.openjdk.jmh.runner.ForkedMain

And then I've stopped!

Any help from your side?

**Comment by tomerr90** [comment]
Huh, thats odd, thanks for letting me know, will definitely check this out!

**Comment by tomerr90** [comment]
OK so notice this code was meant for JDK17 not 21, however I ran the code as is with JDK21 and it also worked.
I just noticed the IntelliJ part, it doesn't work with IntelliJ, I couldn't get maven to pass the run/compile/both (cant remember exactly) args to IntelliJ, IIRC its not supported currently but I might be wrong.
So unfortunately, the best thing I can offer you right now if you want to do work on these files is to make changes in IntelliJ and then compile + run from CLI.
If you run `mvn clean package` + one of the run commands in `runTests.sh` and something doesnt work, please let me know.

**Comment by tomerr90** [comment]
Also tried it with IntelliJ again now, its the run args `--enable-preview --add-modules=jdk.incubator.vector` that I couldnt find a way to pass to IntelliJ, but once I add these manually it runs fine.
I go to SimpleSum, for example, run it through its `main` method, then edit run config to add the VM options above.
Maybe give me some more details about what IntelliJ/Java/OS/Maven are you using and how are you trying to run this?

**Comment by bojanantonovic** [comment]
Thanks for your effort!

I've checked out the project again and found the solution here: https://foojay.io/today/how-to-run-the-java-incubator-module-from-the-command-line-and-intellij-idea, to insert you arguments. What was missing was the entry for "Add VM options".

My project https://github.com/bojanantonovic/vector-api-experiments doesn't do smart things, but the setup is newer, and the JUnit-Tests run out of the box. Even if you create a main-Method in the production code it runs without configuring something.

My environment shouldn't be relevant. It's the latest version of everything on an iMac with M1 CPU.

**Comment by tomerr90** [comment]
So Im a bit confused here, did you get it work? If not, did you try checking out a clean version again and running it like I mentioned above? (`I go to SimpleSum, for example, run it through its main method, then edit run config to add the VM options above.`).
If it doesnt work, what error is IntelliJ showing?

**Comment by bojanantonovic** [comment]
Yes, I managed to run it. ✅
